### ISSUE TITLE
libserialport Migration

### ISSUE THREAD

**Issue by sjkelly** [JuliaIO/SerialPorts.jl#14]
This should help with performance and simplicity. The major question is whether the
Python backend should disappear. I'd like to keep it, but I don't want to sacrifice performance. My
current thought is to make it a build flag, something similar to how PyCall chooses
a python path or anaconda install.

**Comment by andrewadare** [comment]
Hello, I've pretty much done this here: https://github.com/andrewadare/LibSerialPort.jl

I've been using it for several months now on various projects involving microcontrollers, and it seems to be working well for me overall. I took your package as a a guideline while writing the API, so it should look familiar to you if I was successful.

Let me know if you'd like to collaborate on this issue; the legwork of wrapping the C library is done. It's just a matter of refining the interface to match what you have in this package. Glad to help out where I can!

**Comment by andrewadare** [comment]
I should also mention that building and testing on Windows is incomplete, since I'm not much of a Windows user. That's probably the biggest outstanding to-do item.

**Comment by sjkelly** [comment]
Have you registered LibSerialPort yet? How do we want to deal with the license?

**Comment by andrewadare** [comment]
I've avoided registering LibSerialPort.jl, because I was thinking it would be better to integrate it into this package than have two packages with very similar functionality (bigger maintenance burden, confusing for package users, slightly different APIs for no real reason, etc). 

However, the licensing is one consideration (looks like [PySerial is BSD 3-clause](https://github.com/pyserial/pyserial/blob/master/LICENSE.txt)) while libserialport is LGPLv3+. Apparently the [node wrapper](https://github.com/tcr/node-libserialport) adopted that, so there's one precedent. Two obvious options are to change the license here, or to contact the libserialport maintainer(s) about whether they are open to switching to something more permissive.

The other consideration is how to unify the wrapper APIs, since the libraries are not 1:1. Since this package is "established" (i.e. registered) and LibSerialPort.jl is not, I'm fine with changing to the interface for this package as much as possible wherever there are discrepancies. LibSerialPort.jl exposes many additional functions compared to this package, but additions should cause no problem for existing users.

**Comment by sjkelly** [comment]
Excellent, I did not notice libserial port was LGPL3. If you could relicense LibSerialPort.jl as LGPL3 I will relicense SerialPorts as LPGL3 as well. I pulled the commit history/file of LibSerialPort.jl ontop of SerialPorts here as a starting point: https://github.com/JuliaIO/SerialPorts.jl/pull/20
