### ISSUE TITLE
SerialPorts error when writing an UInt8

### ISSUE THREAD

**Issue by kendrick1501** [JuliaIO/SerialPorts.jl#21]
Hi guys!

I am new in julia, and right now I am trying to develop an algorithm to control an RC car from the PC. Thus far I have been able to receive UInt8 data from the vehicle. However, the only data format that is allowed to be from the PC is String, which is a waste of processing time when it comes to "real-time" control.

Is there any way I could send UInt8 data with SerialPorts.write function?

Thanks!

**Comment by sjkelly** [comment]
hi @kendrick1501, cool project. I ran into this recently myself. Unfortunately it is a [limitation of the PySerial backend](https://www.thecodingforums.com/threads/psserial-how-to-write-a-single-byte-value-to-the-serial-port.338172/). https://github.com/JuliaIO/SerialPorts.jl/pull/20 may fix this since we can allocate a buffer and tell it to write one byte without triggering the GC AFAICT.

**Comment by kendrick1501** [comment]
Hi @sjkelly, Thanks for the prompt reply.

Well, I look forward to the LibSerialPort for windows then. Meanwhile, I will be using strings :(
